### ISSUE TITLE
Support to Apollo client cached props

### ISSUE THREAD

**Issue by lucasfeliciano** [NoamELB/make-controllable#2]
I'm facing a interesting problem:

When using apollo client with react once you make a query the results are cached.

So if you navigate using react router or something that doesn't clean the application's memory, when the component is rerendered the `this.props.value` is the same as `nexProps.value` not setting the state with the initial value.

**Comment by NoamELB** [comment]
Hi @lucasfeliciano, this problem seems very odd.
Is there any other way to know that value had changed in this situation?
Mind providing a live example I can play with?
